libxl: fix build on 32-bit
aab4d1b266ce "libxl: Add qxl vga interface support for upstream qemu"
introduced:
	libxl_dm.c: In function ‘libxl__build_device_model_args_new’:
	libxl_dm.c:449: error: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘long long unsigned int’
	libxl_dm.c:451: error: format ‘%lu’ expects type ‘long unsigned int’, but argument 3 has type ‘long long unsigned int’

on arm32 and x86_32.

Use the inttypes.h PRId64 macro.

Signed-off-by: Ian Campbell <ian.campbell@citrix.com>