xsm: fix printf format string for strlen result
strlen returns size_t:

policydb.c: In function policydb_read:
policydb.c:1779: error: format %lu expects type long unsigned int, but argument 3 has type size_t

This is probably benign on 64-bit x86 but was found by Dharshini on 32-bit Xen
4.2.x. I expect it affects ARM too.

Reported-by: Dharshini Tharmaraj <dharshinitharmaraj@gmail.com>
Signed-off-by: Ian Campbell <ian.campbell@citrix.com>
Acked-by: Daniel De Graaf <dgdegra@tycho.nsa.gov>